version: "3.9"

services:
  db:
    image: postgres:15
    container_name: invoiceflow-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: invoiceflow
      POSTGRES_PASSWORD: invoiceflow
      POSTGRES_DB: invoiceflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
